apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-test2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-test2 
  name: demo-test2
  namespace: demo-test2
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: demo-test2 
